[build]
  command = "npm install --prefix netlify/functions && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
